### PR TITLE
Migrate from Travis to GHA

### PR DESCRIPTION
**Pull request by mscrivo**
As per title

### CODE REVIEW

**Comment by mscrivo** [comment]
FYI @dblock

**Comment by dblock** [comment]
Looks good! Update badge(s) in README? Edit CHANGELOG? Also let's re-add Danger, https://github.com/ruby-grape/grape/blob/master/.github/workflows/danger.yml

**Comment by dblock** [comment]
@mscrivo Want to help us maintain this gem, too? If yes, drop me a note to dblock[at]dblock[dot]org and I'll add you to rubygems.

**Comment by dblock** [comment]
Merged this. Want to kick another trivial PR and see if this all worked?

**Pull request merged**
