### PR TITLE
adds support for own format, refactoring

### PR DESCRIPTION
**Pull request by LeFnord**

### CODE REVIEW

**Comment by Bugagazavr** [comment]
@LeFnord let me know, when this to be ready for merge

**Comment by LeFnord** [comment]
@Bugagazavr … yeap now it is ready to merge, had some issues together with grape-swagger,
maybe you can also relase version 0.1.6 😉 … thanks

**Comment by Bugagazavr** [comment]
0.1.6 released

**Comment by LeFnord** [comment]
thanks

**Pull request merged**
