### PR TITLE
Pass extension documentation into schema

### PR DESCRIPTION
**Pull request by numbata**
This PR allows to handle `x-` extension documentation specifically for object type fields in the OpenAPI schema.

For example, it helps to make some fields nullable without modifying the referenced object type with a `x-nullable: true` option like:
```ruby
expose :foo, using: Foo, documentation: {description: "A foo nullable relation", x: { nullable: true } }
```
and have in the schema:
```yaml
      foo:
        "$ref": "#/definitions/Foo
        x-nullable: true
        description: A foo nullable relation
```

### CODE REVIEW

**Comment by numbata** [comment]
@LeFnord @mscrivo Can you have a look at the PR, please?

**Comment by mscrivo** [comment]
Looks good to me, can we add a test to validate the expected behavior?

**Comment by numbata** [comment]
Actually, I just modified the current one, to ensure that it works as expected.
https://github.com/ruby-grape/grape-swagger-entity/pull/64/files#diff-a82dc4f43547c50c91c3c7c0c0fd378a6c0eacc0b0d3272ec419796ddb44de2fR63-R64

**Comment by numbata** [comment]
Also, I see that the workflow should be updated with a new Ruby version. I will do it in a separate PR.

**Comment by mscrivo** [comment]
also don't forget to add an entry to the changelog

**Comment by numbata** [comment]
> also don't forget to add an entry to the changelog

done here [7245469](https://github.com/ruby-grape/grape-swagger-entity/pull/64/commits/7245469aad87d52c081541cc3df3032870a794a4).

**Review by mscrivo — APPROVED** [review]

**Comment by numbata** [comment]
@mscrivo Thank you for approval!
:fyi: Currently omw in making a PR with updating dependencies for the grape's danger gem.
It should unblock #65 which should unblock this PR.

**Comment by mscrivo** [comment]
Thanks! Will merge this in and try to figure out the danger issues separately and get a release out asap.

**Comment by mscrivo** [comment]
> @mscrivo Thank you for approval! :fyi: Currently omw in making a PR with updating dependencies for the grape's danger gem. It should unblock #65 which should unblock this PR.

Ah I missed this, I had started down the same path: https://github.com/ruby-grape/danger/pull/11  Is that what you were thinking as well?

**Comment by numbata** [comment]
Yeah, the same path. Answered here: https://github.com/ruby-grape/grape-swagger-entity/pull/65#issuecomment-1924619584

**Pull request merged**
