### PR TITLE
Refactored parser code

### PR DESCRIPTION
**Pull request by dmitry**
Once I had to read it I found it's not easy to follow the code, so I refactored it.

### CODE REVIEW

**Comment by Bugagazavr** [comment]
Hi, thank you for your contribution, but your changes brokes tests inside grape-swagger.
Looks like something going wrong instead a recursive refs, you just got one entity instead three.

You can reproduce that, but you need clone grape-swagger, and edit Gemfile, puts something like:

```rb
gem 'grape-swagger-entity', path: '../grape-swagger-entity'
```

And launch `MODEL_PARSER=grape-swagger-entity bundle exec rspec`.

Let me know if you have any questions.
Thanks.

**Comment by dblock** [comment]
This also means that this project lacks a spec! Thanks for looking at this @dmitry.

**Comment by Bugagazavr** [comment]
@dblock yep, i think about cloning grape-swagger, and launch grape-swagger specs too, this is one of reason why i suggest store grape-swagger-* gems in one repository with a grape-swagger.

**Comment by dmitry** [comment]
@Bugagazavr fixed an issue. Additionally I found the line:

https://github.com/ruby-grape/grape-swagger-entity/pull/5/commits/4352bce107b93611dd222959bfda49925369f8b9#diff-86e6a3bcefc07f44e39ea5cfc0d1c222R87

Always returns a false, as `!type` means false, when before it says it should be at least `true`. So `ambiguous_model_type?` does nothing. You can just remove ` || ambiguous_model_type?(value[:type])` from `direct_model_type?(value[:type]) || ambiguous_model_type?(value[:type])` and the code will still work.

I believe this `could_it_be_a_model?` not well tested at all, but at least it's now more readable.

**Comment by dmitry** [comment]
By storing `grape-swagger-*` gems inside the `grape-swagger` it will be impossible to create a parsers outside of the `grape-swagger`, by testing them well.

**Comment by dblock** [comment]
I'm with @dmitry, I think having separate gems is good. Just look at Rails ... :)

**Comment by dblock** [comment]
@Bugagazavr I'll leave this PR to you

**Comment by Bugagazavr** [comment]
Good, thanks 👍

**Pull request merged**
