### PR TITLE
adds support for default value

### PR DESCRIPTION
**Pull request by LeFnord**
- updates travis
- updates dependencies
- adds deprecation warning

### CODE REVIEW

**Comment by LeFnord** [comment]
@Bugagazavr … maybe you can give me the rights to maintain this gem too?

**Comment by Bugagazavr** [comment]
@LeFnord you need ask @dblock i have no admin rights :)

**Comment by LeFnord** [comment]
@Bugagazavr thanks, but is it ok for you?
@dblock … see above 😉

**Comment by Bugagazavr** [comment]
@LeFnord Yep, it's ok for me

**Pull request merged**
